{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "29eb8332",
   "metadata": {},
   "source": [
    "# Merge the errors from different tests"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "232524a8",
   "metadata": {},
   "source": [
    "Specify the folder from where you want to import json for analysis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1398615e",
   "metadata": {},
   "outputs": [],
   "source": [
    "path_dir = 'json_analytics_from_test'"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1edb55bc",
   "metadata": {},
   "source": [
    "Specify the number of the last lines for which to merge errors"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "55a90fd5",
   "metadata": {},
   "outputs": [],
   "source": [
    "number_line = 9"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "335a6841",
   "metadata": {},
   "source": [
    "The following block is needed to import the module from the parent folder"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "f71277d7",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import sys\n",
    "import inspect\n",
    "\n",
    "currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))\n",
    "parentdir = os.path.dirname(currentdir)\n",
    "sys.path.insert(0, parentdir) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "b954bd8e",
   "metadata": {},
   "outputs": [],
   "source": [
    "from ParseOutputPytest import ParseOutputPytest\n",
    "pop = ParseOutputPytest()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "06c462e9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Get a list of tests in the folder\n",
    "import os\n",
    "list_files = tuple(os.walk(path_dir))[0][2]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "5d6c4c20",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Get for each file - dict\n",
    "list_dict = []\n",
    "for name_file_test in list_files:\n",
    "    new_dict = pop.get_dict_name_with_error_text(f'{path_dir}\\\\{name_file_test}')\n",
    "    list_dict.append(new_dict)\n",
    "\n",
    "# Merge dicts in one dict\n",
    "res_dict = {}\n",
    "for dict_for_test in list_dict:\n",
    "    res_dict.update(dict_for_test)\n",
    "    \n",
    "# Group the names by errors\n",
    "res_dict_group = pop.get_dict_error_with_list_test(res_dict, number_line)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "e2f9865b",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Total errors:   8934\n",
      "Unique errors:  135\n"
     ]
    }
   ],
   "source": [
    "print(\"Total errors:  \", len(res_dict))\n",
    "print(\"Unique errors: \", len(res_dict_group))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "4bfa1313",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-----------------------------------------------------------------------\n",
      "======= Remote Traceback =======\n",
      " ... \n",
      "E     File \"C:\\Users\\alozovsk\\Anaconda3\\envs\\modin\\lib\\site-packages\\rpyc\\core\\brine.py\", line 194, in _dump\n",
      "E       _dump_registry.get(type(obj), _undumpable)(obj, stream)\n",
      "E     File \"C:\\Users\\alozovsk\\Anaconda3\\envs\\modin\\lib\\site-packages\\rpyc\\core\\brine.py\", line 186, in _dump_tuple\n",
      "E       _dump(item, stream)\n",
      "E     File \"C:\\Users\\alozovsk\\Anaconda3\\envs\\modin\\lib\\site-packages\\rpyc\\core\\brine.py\", line 194, in _dump\n",
      "E       _dump_registry.get(type(obj), _undumpable)(obj, stream)\n",
      "E     File \"C:\\Users\\alozovsk\\Anaconda3\\envs\\modin\\lib\\site-packages\\rpyc\\core\\brine.py\", line 190, in _undumpable\n",
      "E       raise TypeError(\"cannot dump %r\" % (obj,))\n",
      "E   TypeError: cannot dump <member '____id_pack__' of 'BaseNetref' objects> \n",
      "\n",
      "Occurs in 3260 tests.\n",
      "     modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_True-first-quicksort-inplace_True-ascending_True-over_rows_int-multiindex_level0-int_data]\n",
      "     modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_True-first-quicksort-inplace_True-ascending_True-over_rows_int-multiindex_level0-float_nan_data]\n",
      "     modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_True-first-quicksort-inplace_True-ascending_True-over_rows_int-multiindex_level1,multiindex_level0-int_data]\n",
      "     modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_True-first-quicksort-inplace_True-ascending_True-over_rows_int-multiindex_level1,multiindex_level0-float_nan_data]\n",
      "     modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_True-first-quicksort-inplace_True-ascending_True-over_rows_int-multiindex_level0,last,first,multiindex_level1-int_data]\n",
      "And also in 3255 tests.\n",
      "-----------------------------------------------------------------------\n",
      "\n",
      "\n",
      "-----------------------------------------------------------------------\n",
      "modin\\pandas\\test\\test_series.py:187: in create_test_series\n",
      "    modin_series = pd.Series(vals[next(iter(vals.keys()))], **kwargs)\n",
      "modin\\experimental\\cloud\\meta_magic.py:155: in __new__\n",
      "    return cls.__real_cls__(*a, **kw)\n",
      "modin\\experimental\\cloud\\rpyc_proxy.py:431: in __init__\n",
      "    if hasattr(self, \"_preprocess_init_args\"):\n",
      "modin\\experimental\\cloud\\rpyc_proxy.py:497: in __getattribute__\n",
      "    return getattr(dct[\"__remote_end__\"], name)\n",
      "E   KeyError: '__remote_end__' \n",
      "\n",
      "Occurs in 1799 tests.\n",
      "     modin/pandas/test/test_series.py::test_to_frame[int_data]\n",
      "     modin/pandas/test/test_series.py::test_to_frame[float_nan_data]\n",
      "     modin/pandas/test/test_series.py::test_callable_key_in_getitem[int_data]\n",
      "     modin/pandas/test/test_series.py::test_callable_key_in_getitem[float_nan_data]\n",
      "     modin/pandas/test/test_series.py::test_T[int_data]\n",
      "And also in 1794 tests.\n",
      "-----------------------------------------------------------------------\n",
      "\n",
      "\n",
      "-----------------------------------------------------------------------\n",
      "======= Remote Traceback =======\n",
      " ... \n",
      "E     File \"C:\\Users\\alozovsk\\Anaconda3\\envs\\modin\\lib\\site-packages\\rpyc\\core\\protocol.py\", line 338, in _dispatch_request\n",
      "E       res = self._HANDLERS[handler](self, *args)\n",
      "E     File \"C:\\Users\\alozovsk\\Anaconda3\\envs\\modin\\lib\\site-packages\\rpyc\\core\\protocol.py\", line 630, in _handle_call\n",
      "E       return obj(*args, **dict(kwargs))\n",
      "E     File \"C:\\prog\\modin\\modin\\experimental\\cloud\\rpyc_proxy.py\", line 34, in _batch_loads\n",
      "E       return tuple(pickle.loads(item) for item in items)\n",
      "E     File \"C:\\prog\\modin\\modin\\experimental\\cloud\\rpyc_proxy.py\", line 34, in <genexpr>\n",
      "E       return tuple(pickle.loads(item) for item in items)\n",
      "E   AttributeError: type object '_DTypeMeta' has no attribute '_abstract' \n",
      "\n",
      "Occurs in 1634 tests.\n",
      "     modin/pandas/test/dataframe/test_indexing.py::test_loc_nested_assignment[int_data]\n",
      "     modin/pandas/test/dataframe/test_indexing.py::test_loc_nested_assignment[float_nan_data]\n",
      "     modin/pandas/test/dataframe/test_indexing.py::test_iloc_nested_assignment[int_data]\n",
      "     modin/pandas/test/dataframe/test_indexing.py::test_iloc_nested_assignment[float_nan_data]\n",
      "     modin/pandas/test/dataframe/test_indexing.py::test_pop[int_data]\n",
      "And also in 1629 tests.\n",
      "-----------------------------------------------------------------------\n",
      "\n",
      "\n",
      "-----------------------------------------------------------------------\n",
      "modin\\pandas\\test\\test_series.py:190: in create_test_series\n",
      "    modin_series = pd.Series(vals, **kwargs)\n",
      "modin\\experimental\\cloud\\meta_magic.py:155: in __new__\n",
      "    return cls.__real_cls__(*a, **kw)\n",
      "modin\\experimental\\cloud\\rpyc_proxy.py:431: in __init__\n",
      "    if hasattr(self, \"_preprocess_init_args\"):\n",
      "modin\\experimental\\cloud\\rpyc_proxy.py:497: in __getattribute__\n",
      "    return getattr(dct[\"__remote_end__\"], name)\n",
      "E   KeyError: '__remote_end__' \n",
      "\n",
      "Occurs in 1137 tests.\n",
      "     modin/pandas/test/test_series.py::test___setitem___non_hashable[str_index-location_based_slice]\n",
      "     modin/pandas/test/test_series.py::test___setitem___non_hashable[str_index-index_based_slice]\n",
      "     modin/pandas/test/test_series.py::test___setitem___non_hashable[str_index-list_of_labels]\n",
      "     modin/pandas/test/test_series.py::test___setitem___non_hashable[str_index-boolean_mask]\n",
      "     modin/pandas/test/test_series.py::test___setitem___non_hashable[int_index-location_based_slice]\n",
      "And also in 1132 tests.\n",
      "-----------------------------------------------------------------------\n",
      "\n",
      "\n",
      "-----------------------------------------------------------------------\n",
      "======= Remote Traceback =======\n",
      " ... \n",
      "E     File \"C:\\Users\\alozovsk\\Anaconda3\\envs\\modin\\lib\\site-packages\\rpyc\\core\\protocol.py\", line 338, in _dispatch_request\n",
      "E       res = self._HANDLERS[handler](self, *args)\n",
      "E     File \"C:\\Users\\alozovsk\\Anaconda3\\envs\\modin\\lib\\site-packages\\rpyc\\core\\protocol.py\", line 630, in _handle_call\n",
      "E       return obj(*args, **dict(kwargs))\n",
      "E     File \"C:\\prog\\modin\\modin\\experimental\\cloud\\rpyc_proxy.py\", line 34, in _batch_loads\n",
      "E       return tuple(pickle.loads(item) for item in items)\n",
      "E     File \"C:\\prog\\modin\\modin\\experimental\\cloud\\rpyc_proxy.py\", line 34, in <genexpr>\n",
      "E       return tuple(pickle.loads(item) for item in items)\n",
      "E   AttributeError: type object 'ndarray' has no attribute '__iter__' \n",
      "\n",
      "Occurs in 120 tests.\n",
      "     modin/pandas/test/dataframe/test_indexing.py::test_rename_sanity\n",
      "     modin/pandas/test/dataframe/test_indexing.py::test_rename_inplace\n",
      "     modin/pandas/test/dataframe/test_indexing.py::test_rename_axis_inplace\n",
      "     modin/pandas/test/dataframe/test_indexing.py::test_reorder_levels\n",
      "     modin/pandas/test/dataframe/test_indexing.py::test_reindex_multiindex\n",
      "And also in 115 tests.\n",
      "-----------------------------------------------------------------------\n",
      "\n",
      "\n",
      "-----------------------------------------------------------------------\n",
      "E   _get_exception_class.<locals>.Derived: 'list' object is not callable\n",
      "E   \n",
      "E   ========= Remote Traceback (1) =========\n",
      "E   Traceback (most recent call last):\n",
      "E     File \"C:\\Users\\alozovsk\\Anaconda3\\envs\\modin\\lib\\site-packages\\rpyc\\core\\protocol.py\", line 338, in _dispatch_request\n",
      "E       res = self._HANDLERS[handler](self, *args)\n",
      "E     File \"C:\\Users\\alozovsk\\Anaconda3\\envs\\modin\\lib\\site-packages\\rpyc\\core\\protocol.py\", line 630, in _handle_call\n",
      "E       return obj(*args, **dict(kwargs))\n",
      "E   TypeError: 'list' object is not callable \n",
      "\n",
      "Occurs in 117 tests.\n",
      "     modin/pandas/test/dataframe/test_default.py::test_take\n",
      "     modin/pandas/test/dataframe/test_indexing.py::test_asof_with_nan[subset2-dates0]\n",
      "     modin/pandas/test/dataframe/test_indexing.py::test_asof_with_nan[subset2-dates1]\n",
      "     modin/pandas/test/dataframe/test_indexing.py::test_asof_without_nan[subset2-dates0]\n",
      "     modin/pandas/test/dataframe/test_indexing.py::test_asof_without_nan[subset2-dates1]\n",
      "And also in 112 tests.\n",
      "-----------------------------------------------------------------------\n",
      "\n",
      "\n",
      "-----------------------------------------------------------------------\n",
      "======= Remote Traceback =======\n",
      " ... \n",
      "E     File \"C:\\prog\\modin\\modin\\pandas\\dataframe.py\", line 172, in __init__\n",
      "E       pandas_df = pandas.DataFrame(\n",
      "E     File \"C:\\Users\\alozovsk\\Anaconda3\\envs\\modin\\lib\\site-packages\\pandas\\core\\frame.py\", line 702, in __init__\n",
      "E       mgr = arrays_to_mgr(\n",
      "E     File \"C:\\Users\\alozovsk\\Anaconda3\\envs\\modin\\lib\\site-packages\\pandas\\core\\internals\\construction.py\", line 135, in arrays_to_mgr\n",
      "E       return create_block_manager_from_arrays(\n",
      "E     File \"C:\\Users\\alozovsk\\Anaconda3\\envs\\modin\\lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 1776, in create_block_manager_from_arrays\n",
      "E       raise construction_error(len(arrays), arrays[0].shape, axes, e)\n",
      "E   ValueError: Shape of passed values is (4, 4), indices imply (2, 4) \n",
      "\n",
      "Occurs in 77 tests.\n",
      "     modin/pandas/test/dataframe/test_reduction.py::test_prod[data0-over_rows_int-skipna_True-False-prod]\n",
      "     modin/pandas/test/dataframe/test_reduction.py::test_prod[data0-over_rows_int-skipna_True-False-product]\n",
      "     modin/pandas/test/dataframe/test_reduction.py::test_prod[data0-over_rows_int-skipna_True-True-prod]\n",
      "     modin/pandas/test/dataframe/test_reduction.py::test_prod[data0-over_rows_int-skipna_True-True-product]\n",
      "     modin/pandas/test/dataframe/test_reduction.py::test_prod[data0-over_rows_int-skipna_False-False-prod]\n",
      "And also in 72 tests.\n",
      "-----------------------------------------------------------------------\n",
      "\n",
      "\n",
      "-----------------------------------------------------------------------\n",
      "======= Remote Traceback =======\n",
      " ... \n",
      "E     File \"C:\\Users\\alozovsk\\Anaconda3\\envs\\modin\\lib\\site-packages\\rpyc\\core\\protocol.py\", line 656, in _handle_callattr\n",
      "E       return self._handle_call(obj, args, kwargs)\n",
      "E     File \"C:\\Users\\alozovsk\\Anaconda3\\envs\\modin\\lib\\site-packages\\rpyc\\core\\protocol.py\", line 630, in _handle_call\n",
      "E       return obj(*args, **dict(kwargs))\n",
      "E     File \"C:\\Users\\alozovsk\\Anaconda3\\envs\\modin\\lib\\site-packages\\pandas\\core\\indexes\\multi.py\", line 2060, in __getitem__\n",
      "E       new_codes = [level_codes[key] for level_codes in self.codes]\n",
      "E     File \"C:\\Users\\alozovsk\\Anaconda3\\envs\\modin\\lib\\site-packages\\pandas\\core\\indexes\\multi.py\", line 2060, in <listcomp>\n",
      "E       new_codes = [level_codes[key] for level_codes in self.codes]\n",
      "E   IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices \n",
      "\n",
      "Occurs in 72 tests.\n",
      "     modin/pandas/test/dataframe/test_binary.py::test_math_functions_level[add]\n",
      "     modin/pandas/test/dataframe/test_binary.py::test_math_functions_level[radd]\n",
      "     modin/pandas/test/dataframe/test_binary.py::test_math_functions_level[sub]\n",
      "     modin/pandas/test/dataframe/test_binary.py::test_math_functions_level[rsub]\n",
      "     modin/pandas/test/dataframe/test_binary.py::test_math_functions_level[mod]\n",
      "And also in 67 tests.\n",
      "-----------------------------------------------------------------------\n",
      "\n",
      "\n",
      "-----------------------------------------------------------------------\n",
      "modin\\pandas\\test\\test_series.py:370: in test___getitem_edge_cases\n",
      "    modin_series = pd.Series(data)\n",
      "modin\\experimental\\cloud\\meta_magic.py:155: in __new__\n",
      "    return cls.__real_cls__(*a, **kw)\n",
      "modin\\experimental\\cloud\\rpyc_proxy.py:431: in __init__\n",
      "    if hasattr(self, \"_preprocess_init_args\"):\n",
      "modin\\experimental\\cloud\\rpyc_proxy.py:497: in __getattribute__\n",
      "    return getattr(dct[\"__remote_end__\"], name)\n",
      "E   KeyError: '__remote_end__' \n",
      "\n",
      "Occurs in 64 tests.\n",
      "     modin/pandas/test/test_series.py::test___getitem_edge_cases[-7--7]\n",
      "     modin/pandas/test/test_series.py::test___getitem_edge_cases[-7--5]\n",
      "     modin/pandas/test/test_series.py::test___getitem_edge_cases[-7--3]\n",
      "     modin/pandas/test/test_series.py::test___getitem_edge_cases[-7-0]\n",
      "     modin/pandas/test/test_series.py::test___getitem_edge_cases[-7-None]\n",
      "And also in 59 tests.\n",
      "-----------------------------------------------------------------------\n",
      "\n",
      "\n",
      "-----------------------------------------------------------------------\n",
      "modin\\experimental\\cloud\\rpyc_proxy.py:483: in __getattribute__\n",
      "    return oget(self, type(self))\n",
      "modin\\experimental\\cloud\\rpyc_proxy.py:602: in iloc\n",
      "    return DeliveringILocIndexer(self.__remote_end__)\n",
      "modin\\experimental\\cloud\\rpyc_proxy.py:431: in __init__\n",
      "    if hasattr(self, \"_preprocess_init_args\"):\n",
      "modin\\experimental\\cloud\\rpyc_proxy.py:497: in __getattribute__\n",
      "    return getattr(dct[\"__remote_end__\"], name)\n",
      "E   KeyError: '__remote_end__' \n",
      "\n",
      "Occurs in 59 tests.\n",
      "     modin/pandas/test/dataframe/test_binary.py::test_math_functions[add-columns-series_or_list]\n",
      "     modin/pandas/test/dataframe/test_binary.py::test_math_functions[radd-columns-series_or_list]\n",
      "     modin/pandas/test/dataframe/test_binary.py::test_math_functions[sub-columns-series_or_list]\n",
      "     modin/pandas/test/dataframe/test_binary.py::test_math_functions[rsub-columns-series_or_list]\n",
      "     modin/pandas/test/dataframe/test_binary.py::test_math_functions[mod-columns-series_or_list]\n",
      "And also in 54 tests.\n",
      "-----------------------------------------------------------------------\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "pop.print_top_most_frequent_errors(res_dict, number_line, 10)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
